apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.ASPNETCORE_ENVIRONMENT | quote }}

  # OTEL_EXPORTER for Grafana OTEL
  OTEL_EXPORTER_OTLP_ENDPOINT:
    {{ .Values.config.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}

  # Security settings
  Security__SecretKey: {{ .Values.config.Security__SecretKey | quote }}
  Security__Issuer: {{ .Values.config.Security__Issuer | quote }}
  Security__Audience: {{ .Values.config.Security__Audience | quote }}
  Security__AccessTokenLifetimeInMinutes:
    {{ .Values.config.Security__AccessTokenLifetimeInMinutes | quote }}
  Security__RefreshTokenLifetimeInMinutes:
    {{ .Values.config.Security__RefreshTokenLifetimeInMinutes | quote }}

  # Redis connection string for caching
  RedisSettings__ConnectionString:
    {{ .Values.config.RedisSettings__ConnectionString | quote }}

  # gRPC service URL
  GrpcSettings__IdentityServiceUrl:
    {{ .Values.config.GrpcSettings__IdentityServiceUrl | quote }}

  # Database Connections
  CatalogDb__ConnectionString:
    {{ .Values.config.CatalogDb__ConnectionString | quote }}
  IdentityDb__ConnectionString:
    {{ .Values.config.IdentityDb__ConnectionString | quote }}

  # RabbitMQ
  EventBusSettings__HostAddress:
    {{ .Values.config.EventBusSettings__HostAddress | quote }}
  RABBITMQ_DEFAULT_USER: {{ .Values.config.RABBITMQ_DEFAULT_USER | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.config.RABBITMQ_DEFAULT_PASS | quote }}

  # SQL Server
  MSSQL_SA_PASSWORD: {{ .Values.config.MSSQL_SA_PASSWORD | quote }}
