apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisinsight-pvc
  namespace: ecommerce
  labels:
    app: redisinsight

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi
      
