apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: ecommerce
  labels:
    app: redisinsight

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redisinsight

  template:
    metadata:
      labels:
        app: redisinsight

    spec:
      containers:
        - name: redisinsight
          image: redis/redisinsight:3.8.0

          ports:
            - name: http
              containerPort: 5540
              protocol: TCP

          env:
            - name: RI_PROXY_PATH
              value: /redisinsight

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            - name: redisinsight-data
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /redisinsight/
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /redisinsight/
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

      volumes:
        - name: redisinsight-data
          persistentVolumeClaim:
            claimName: redisinsight-pvc
