apiVersion: v1
kind: Service
metadata:
  name: otel-lgtm
  namespace: ecommerce
spec:
  type: ClusterIP

  selector:
    app: otel-lgtm

  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      protocol: TCP

    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP

    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
