{{- if .Values.infrastructure.redisinsight.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.infrastructure.redisinsight.name }}
  namespace:  {{ .Values.global.namespace }}
  labels:
    app:  {{ .Values.infrastructure.redisinsight.name }}

spec:
  type: {{ .Values.infrastructure.redisinsight.service.type }}

  selector:
    app:  {{ .Values.infrastructure.redisinsight.name }}

  ports:
    - name: http
      port: {{ .Values.infrastructure.redisinsight.service.port }}
      targetPort: http
      protocol: TCP
      
{{- end }}