services:
  discount.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8002:80"

  catalog.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDbSettings__ConnectionString: mongodb://admin:pass_123456789@mongodb:27017
      MongoDbSettings__DatabaseName: Catalog
      SQLServerSettings__ConnectionString: Server=sqlserver,1433;Database=Catalog;User Id=sa;Password=pass_123456789;TrustServerCertificate=True;
      PostgreSQLSettings__ConnectionString: Host=postgres;Port=5432;Database=Catalog;User Id=admin;Password=pass_123456789;
      RedisSettings__ConnectionString: redis:6379
      GrpcSettings__DiscountUrl: http://discount.api
      EventBusSettings__HostAddress: amqp://admin:pass_123456789@rabbitmq:5672
    depends_on:
      mongodb:
        condition: service_healthy
      sqlserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8001:80"

  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass_123456789
    ports:
      - "2001:27017"
    healthcheck:
      test: ["CMD-SHELL","mongosh --host localhost --port 27017 -u admin -p pass_123456789 --authenticationDatabase admin --eval \"db.adminCommand('ping').ok\" --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  sqlserver:
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: pass_123456789
    ports:
      - "2002:1433"
    healthcheck:
      test: ["CMD-SHELL","/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'pass_123456789' -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  postgres:
    environment:
      POSTGRES_DB: Catalog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass_123456789
    ports:
      - "2003:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d Catalog"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass_123456789
    ports:
      - "2004:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s





