services:

 gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    restart: always
    build:
      context: .
      dockerfile: Gateway/Gateway.api/Dockerfile
    ports:
      - "80:80"
      - "81:81"
 
 identity-api:
    image: ${DOCKER_REGISTRY-}identity-api
    restart: always
    build:
      context: ..
      dockerfile: Source/Services/Identity/Identity.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      IdentityDb__ConnectionString: ${IdentityDb__ConnectionString}
      GrpcSettings__IdentityServiceUrl: ${GrpcSettings__IdentityServiceUrl}
      EventBusSettings__HostAddress: ${EventBusSettings__HostAddress}
      Security__SecretKey: ${Security__SecretKey}
      Security__Issuer: "${Security__Issuer}"
      Security__Audience: "${Security__Audience}"
      Security__AccessTokenLifetimeInMinutes: ${Security__AccessTokenLifetimeInMinutes}    # 1 Hour
      Security__RefreshTokenLifetimeInMinutes: ${Security__RefreshTokenLifetimeInMinutes} # 24 hours
   

 # report.api:
 #  image: ${DOCKER_REGISTRY-}report-api
 #  build:
 #    context: .
 #    dockerfile: Services/Report/Report.API/Dockerfile

 catalog-api:
    image: ${DOCKER_REGISTRY-}catalog-api
    restart: always
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      CatalogDb__ConnectionString: ${CatalogDb__ConnectionString}
      RedisSettings__ConnectionString: ${RedisSettings__ConnectionString}
      GrpcSettings__DiscountUrl: ${GrpcSettings__DiscountUrl}
      HttpClient__DiscountUrl: ${HttpClient__DiscountUrl}
      GrpcSettings__IdentityServiceUrl: ${GrpcSettings__IdentityServiceUrl}
      EventBusSettings__HostAddress: ${EventBusSettings__HostAddress}
      Security__SecretKey: ${Security__SecretKey}
      Security__Issuer: "${Security__Issuer}"
      Security__Audience: "${Security__Audience}"
    depends_on:
      mongodb:
        condition: service_healthy
      sqlserver:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


 mongodb:
   image: mongo:8.3.8
   restart: always
   volumes:
     - mongo_data:/data/db
   environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
   healthcheck:
      test: ["CMD-SHELL","mongosh --host localhost --port 27017 -u admin -p $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval \"db.adminCommand('ping').ok\" --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
   ports:
      - "2001:27017"

 sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql 
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL","/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${MSSQL_SA_PASSWORD} -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "2002:1433"
  
 postgres:
    image: postgres:18.6
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d Catalog"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "2003:5432"
  
 redis:
    image: redis:8.2
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
 rabbitmq:
    image: rabbitmq:4.2-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "2004:15672"

 portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "2005:9000"


 redisinsight:
    image: redis/redisinsight:latest
    restart: always
    volumes:
        - redisinsight_data:/data
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "2006:5540"
 
 

volumes:
  mongo_data:
  sqlserver_data:
  postgres_data:
  rabbitmq_data:
  portainer_data:
  redisinsight_data:
  

  


