services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    restart: always
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - catalogmongodb 
    environment:
      - ASPNETCORE_HTTP_PORTS=80
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__ProductCollectionName=Products"
      - "DatabaseSettings__BrandCollectionName=Brands"
      - "DatabaseSettings__TypeCollectionName=Types"

  catalogmongodb:
   image: mongo
   restart: always
   volumes:
     - mongo_data:/data/db
       
volumes:
  mongo_data:
  
  


  