services:
  discount.api:
    image: ${DOCKER_REGISTRY-}discount-api
    restart: always
    build:
      context: .
      dockerfile: Services/Discount/Discount.api/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog-api
    restart: always
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=80

  mongodb:
   image: mongo:8.3.8
   restart: always
   volumes:
     - mongo_data:/data/db

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql 
  
  postgres:
    image: postgres:18.6
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
  
  redis:
    image: redis:8.2
    restart: always
  
  rabbitmq:
    image: rabbitmq:4.2-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  sqlserver_data:
  postgres_data:
  rabbitmq_data:
  

  


  
