services:
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discount-grpc
    restart: always
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog-api
    restart: always
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    depends_on:
      - mongodb 
      - sqlserver
      - postgres
      - redis
    environment:
      - ASPNETCORE_HTTP_PORTS=80

  mongodb:
   image: mongo:latest
   restart: always
   volumes:
     - mongo_data:/data/db

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    volumes:
      - sqlserver_data:/var/opt/mssql 
  
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
  
  redis:
    image: redis:latest
    restart: always


volumes:
  mongo_data:
  sqlserver_data:
  postgres_data:
  
  


  
