apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDBTCCAe2gAwIBAgIIeraFyLawKngwDQYJKoZIhvcNAQELBQAwFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczAeFw0yNjA5MjkxNzUyMzhaFw0zNjA5MjYxNzU3MzhaMBUx
    EzARBgNVBAMTCmt1YmVybmV0ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQCnxzPjGLKYvwGVgv+iAe47O4mk1vvpfOl3wsGPfg3zBnIauq+xKkHsRrVT
    z/0CY/sKDLgpbQEV+R5XT36uCXDbPR/iJH5OhrFPwFlfIIZSbR0SUQ7D6YKqYEgU
    EvywLa5R/zPXAwEBbpLrhzkHxOA3rcdK/szenKcGU2nql+z0xjDGvo3TcTivHYbU
    VbEdKcpHqtb/qjK/rVFIJy34MtOGbrnfoySyNWXzWS7QWwUf/Q823J/Eo15hlJPD
    DX7FBbhEZajJ4zPuzTf4i0wISa1A55BMyI3nbWiFew7munV0S357dXEZtEbhwJBO
    gi5FoKEpQbDOCDME7vOcMfb9/2OrAgMBAAGjWTBXMA4GA1UdDwEB/wQEAwICpDAP
    BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQwFDz3hkCxTuoEZFOvXBbJAbPo3TAV
    BgNVHREEDjAMggprdWJlcm5ldGVzMA0GCSqGSIb3DQEBCwUAA4IBAQAr6+sObCyk
    XwoElbm1hZtNyw7JXVUheLH0UdJDyEobNWuwDm92VjGJ9x2ZckjHqIMWDKgiyeMb
    /hIRWma+kh5TW6SO60Wgx93ushMi+YpzRnnHV3rl6v/0eVhZHViy9Re8k480nEe6
    iRPdbHER6vaEy6TUhC7AfbLcViEGE1bIKDHWSV7JFDfqfqGrznS3oVBK0I64y8h8
    fR43VNen/Ya5NnBKDV1ck6IFzXIzbramTmZiG26fUI5CO+Y+6/HxzeCmCdbQmS6D
    tL6gSWk/ybeXj++SUHJlgVHasniMrAk1EkLr811pwYW8KHQ1Mx2PEEx9fFlCFqGJ
    DE7kRYT/HF92
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    kubernetes.io/description: Contains a CA bundle that can be used to verify the
      kube-apiserver when using internal endpoints such as the internal service IP
      or kubernetes.default.svc. No other usage is guaranteed across distributions
      of Kubernetes clusters.
  creationTimestamp: "2026-09-29T17:57:51Z"
  name: kube-root-ca.crt
  namespace: default
  resourceVersion: "367"
  uid: 05f41f7e-34af-4c89-8031-6f709801dc5b
