<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.10" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Platform\Platform.Core\Platform.Core.csproj" />
    <ProjectReference Include="..\Catalog.Domain\Catalog.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Resource.ar.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\Resource.en.resx">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

</Project>
