apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: ecommerce
  labels:
    app: rabbitmq

spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi
      
