<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.2.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.2.0" />
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />
	  <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.11" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
	  <PackageReference Include="OpenTelemetry.Exporter.Console" Version="1.17.0" />
	  <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.17.0" />
	  <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.17.0" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.17.0" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.17.0" />
	  <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.17.0" />
	  <PackageReference Include="Serilog" Version="4.4.0" />
	  <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
	  <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
	  <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
	  <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	  <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Platform.Application\Platform.Application.csproj" />
    <ProjectReference Include="..\Platform.Core\Platform.Core.csproj" />
    <ProjectReference Include="..\Platform.Infrastructure\Platform.Infrastructure.csproj" />
  </ItemGroup>

</Project>
