{{- if .Values.redis.enabled }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.redis.name }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Values.redis.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}

    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.image.repository }}

          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP

          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}

          volumeMounts:
            - name: {{ .Values.redis.name }}-data
              mountPath: /data

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

      volumes:
        - name: {{ .Values.redis.name }}-data
          persistentVolumeClaim:
            claimName: {{ .Values.redis.name }}-pvc

{{- end }}