{{- if .Values.redisinsight.enabled }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.redisinsight.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.redisinsight.name }}

spec:
  replicas: 1

  selector:
    matchLabels:
      app: {{ .Values.redisinsight.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.redisinsight.name }}

    spec:
      containers:
        - name: {{ .Values.redisinsight.name }}
          image: {{ .Values.redisinsight.image.repository }}

          ports:
            - name: http
              containerPort: {{ .Values.redisinsight.service.port }}
              protocol: TCP

          resources:
            {{- toYaml .Values.redisinsight.resources | nindent 12 }}

          volumeMounts:
            - name: redisinsight-data
              mountPath: /data

          readinessProbe:
            httpGet:
              path: /redisinsight/
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /redisinsight/
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

      volumes:
        - name: redisinsight-data
          persistentVolumeClaim:
            claimName: redisinsight-pvc

{{- end }}