global:
  namespace: ecommerce

identity:
  enabled: true
  name: identity-api
  replicas: 2

  image:
    repository: identity-api:1.1.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: http
    protocol: TCP

  serviceGrpc:
    port: 81
    targetPort: grpc
    protocol: TCP

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

fileStorage:
  enabled: true
  name: filestorage-api
  replicas: 2

  image:
    repository: filestorage-api:1.3.0
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: http
    protocol: TCP

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

  persistence:
    size: 100Gi
    storageClass: standard

catalog:
  enabled: true
  name: catalog-api
  replicas: 2

  image:
    repository: catalog-api:1.1.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: http
    protocol: TCP

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

gateway:
  enabled: true
  name: gateway-api
  replicas: 2

  image:
    repository: gateway-api:1.3.0
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: http
    protocol: TCP

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

client:
  enabled: true
  name: ecommerce-client
  replicas: 2

  image:
    repository: client:1.1.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: http
    protocol: TCP

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true

  name: ecommerce-ingress
  className: nginx
  host: ecommerce.local

  tls:
    enabled: true
    secretName: ecommerce-tls

  annotations:
    clusterIssuer: ecommerce-selfsigned
    proxyBodySize: "50m"
    proxyReadTimeout: "120"
    proxySendTimeout: "120"

  paths:
    # Angular client
    - path: /
      pathType: Prefix
      service:
        name: ecommerce-client
        port: 80

    # Gateway
    - path: /api
      pathType: Prefix
      service:
        name: gateway-api
        port: 80

config:
  ASPNETCORE_ENVIRONMENT: Staging

  # OTEL_EXPORTER for Grafana OTEL
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-lgtm:4318

  # Security settings
  Security__SecretKey: 879b274c-9cab-4afa-a868-bf5d3038c8d7
  Security__Issuer: "ecommerce.identity"
  Security__Audience: "ecommerce.clients"
  Security__AccessTokenLifetimeInMinutes: "60" # 1 Hour
  Security__RefreshTokenLifetimeInMinutes: "1440" # 24 hours

  # Redis connection string for caching
  RedisSettings__ConnectionString: redis:6379

  # gRPC service URL
  GrpcSettings__IdentityServiceUrl: http://identity-api:81

  # Database Connections
  CatalogDb__ConnectionString: Server=sqlserver,1433;Database=CatalogDb;User Id=sa;Password=pass_123456789;TrustServerCertificate=True;
  IdentityDb__ConnectionString: Server=sqlserver,1433;Database=IdentityDb;User Id=sa;Password=pass_123456789;TrustServerCertificate=True;
  
  MongoDB__ConnectionString: mongodb://admin:pass_123456789@mongodb:27017
  FileStorage__DatabaseName: FileStorageDB
  
  # RabbitMQ
  EventBusSettings__HostAddress: amqp://admin:pass_123456789@rabbitmq:5672
