{{- if .Values.infrastructure.rabbitmq.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.infrastructure.rabbitmq.name }}
  namespace:  {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.infrastructure.rabbitmq.name }}

spec:
  type: {{ .Values.infrastructure.rabbitmq.service.type }}

  selector:
    app: {{ .Values.infrastructure.rabbitmq.name }}

  ports:
    - name: amqp
      port: {{ .Values.infrastructure.rabbitmq.service.amqpPort }}
      targetPort: 5672
      protocol: TCP

    - name: management
      port: {{ .Values.infrastructure.rabbitmq.service.managementPort }}
      targetPort: 15672
      protocol: TCP
{{- end }}