apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
data:
  # Security settings
  Security__SecretKey: ODc5YjI3NGMtOWNhYi00YWZhLWE4NjgtYmY1ZDMwMzhjOGQ=

  # Database connection strings
  CatalogDb__ConnectionString: U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPUNhdGFsb2dEYjtVc2VyIElkPXNhO1Bhc3N3b3JkPXBhc3NfMTIzNDU2Nzg5O1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTs=
  IdentityDb__ConnectionString: U2VydmVyPXNxbHNlcnZlciwxNDMzO0RhdGFiYXNlPUlkZW50aXR5RGI7VXNlciBJZD1zYTtQYXNzd29yZD1wYXNzXzEyMzQ1Njc4OTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPVRydWU7

  # RabbitMQ
  EventBusSettings__HostAddress: YW1xcDovL2FkbWluOnBhc3NfMTIzNDU2Nzg5QHJhYmJpdG1xOjU2NzI=

  # SQL Server
  MSSQL_SA_PASSWORD: cGFzc18xMjM0NTY3ODk=

  # RabbitMQ
  RABBITMQ_DEFAULT_USER: YWRtaW4=
  RABBITMQ_DEFAULT_PASS: cGFzc18xMjM0NTY3ODk=
