<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Persistence\Seed\Data\brands.json" />
    <None Remove="Persistence\Seed\Data\products.json" />
    <None Remove="Persistence\Seed\Data\types.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Persistence\Seed\Data\brands.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Persistence\Seed\Data\products.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Persistence\Seed\Data\types.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
	  <PackageReference Include="Riok.Mapperly" Version="4.3.1" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Platform\Platform.Infrastructure\Platform.Infrastructure.csproj" />
    <ProjectReference Include="..\Catalog.Core\Catalog.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\PostgreSQL\Migrations\" />
    <Folder Include="Persistence\SQLServer\Migrations\" />
  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Grpc.Net.ClientFactory" Version="2.83.0" />
		<PackageReference Include="Google.Protobuf" Version="3.33.0" />
		<PackageReference Include="Grpc.Tools" Version="2.83.0">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup>
		<Protobuf Include="..\..\..\Contracts\Grpc\discount.proto" GrpcServices="Client" />
	</ItemGroup>
	
</Project>
