{{- if .Values.catalog.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.catalog.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.catalog.service.type }}

  selector:
    app: {{ .Values.catalog.name }}

  ports:
    - name: http
      port: {{ .Values.catalog.service.port }}
      targetPort: {{ .Values.catalog.service.targetPort }}
      protocol: {{ .Values.catalog.service.protocol }}
      
{{- end }}