apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-infrastructure-config
  namespace: ecommerce
data:

  # RabbitMQ
  RABBITMQ_DEFAULT_USER: {{ .Values.config.RABBITMQ_DEFAULT_USER | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.config.RABBITMQ_DEFAULT_PASS | quote }}

  # SQL Server
  MSSQL_SA_PASSWORD: {{ .Values.config.MSSQL_SA_PASSWORD | quote }}
