{{- if .Values.infrastructure.otelLgtm.enabled }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.infrastructure.otelLgtm.name }}-data
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName:
        {{ .Values.infrastructure.otelLgtm.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.infrastructure.otelLgtm.persistence.size }}
      
        
{{- end }}