syntax = "proto3";

option csharp_namespace = "Catalog.GRPC";

package Catalog;

message GetProductsRequest {
  optional string brand_id = 1;
  optional string type_id = 2;

}

message GetProductsResponse {
  string name = 1;
  string summary = 2;
  string description = 3;
  string brand_name = 4;
  string type_name = 5;
  string  price = 6;
  string CreatedDate = 7;
}

message GetProductsResult {
  repeated GetProductsResponse products = 1;
}

service CatalogService {
  rpc GetProducts(GetProductsRequest) returns (GetProductsResult);
}