{{- if .Values.apps.identity.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: { { .Values.apps.identity.name } }
  namespace: { { .Values.global.namespace } }
  labels:
    app: { { .Values.apps.identity.name } }
spec:
  type: ClusterIP

  selector:
    app: { { .Values.apps.identity.name } }

  ports:
    - name: http
      port: { { .Values.apps.identity.service.port } }
      targetPort: { { .Values.apps.identity.service.targetPort } }
      protocol: { { .Values.apps.identity.service.protocol } }

{{- end }}