name: Local
variables:
  - name: access-token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjRlNjQxZC00NzJhLTA4ODEtNzAwMC0wMWEwYjA3NWViZTYiLCJ0b2tlbl90eXBlIjoiYWNjZXNzX3Rva2VuIiwiZXhwIjoxNzkwMzQxNDQ2LCJpc3MiOiJlY29tbWVyY2UuaWRlbnRpdHkiLCJhdWQiOiJlY29tbWVyY2UuY2xpZW50cyJ9.qyVhdtrPV2NCyE210iCSVQ9G-SP5fov5KW8wNqx5jWw
  - name: refresh-token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjRlNjQxZC00NzJhLTA4ODEtNzAwMC0wMWEwYjA3NWViZTYiLCJ0b2tlbl90eXBlIjoicmVmcmVzaF90b2tlbiIsImV4cCI6MTc5MDM0MTQ0NiwiaXNzIjoiZWNvbW1lcmNlLmlkZW50aXR5IiwiYXVkIjoiZWNvbW1lcmNlLmNsaWVudHMifQ.FxLRwwYZGq_rPB4UObRS0tZUV6SlOYydrQ9oBIah6Oc
  - name: URL
    value: localhost
