name: Local
variables:
  - name: access-token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5M2Y1NWMzZi1lY2VlLTZlODEtNzAwMC0wMWEwYWMzNTk3MTgiLCJ0b2tlbl90eXBlIjoiYWNjZXNzX3Rva2VuIiwiZXhwIjoxNzg5OTk4MjY4LCJpc3MiOiJlY29tbWVyY2UuaWRlbnRpdHkiLCJhdWQiOiJlY29tbWVyY2UuY2xpZW50cyJ9.0yN3ZTvdTpO29hNiQFOOpX_O9jXC34wCUdu58elDYrI
    description: ""
  - name: refresh-token
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5M2Y1NWMzZi1lY2VlLTZlODEtNzAwMC0wMWEwYWMzNTk3MTgiLCJ0b2tlbl90eXBlIjoicmVmcmVzaF90b2tlbiIsImV4cCI6MTc4OTk5ODI2OCwiaXNzIjoiZWNvbW1lcmNlLmlkZW50aXR5IiwiYXVkIjoiZWNvbW1lcmNlLmNsaWVudHMifQ.W6OcuoMLehKXYfkHZbfjGBooK0j6vR6DvRiie34__Lg
    description: ""
