<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Persistence\Seed\Data\brands.json" />
    <None Remove="Persistence\Seed\Data\products.json" />
    <None Remove="Persistence\Seed\Data\types.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Persistence\Seed\Data\brands.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Persistence\Seed\Data\products.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Persistence\Seed\Data\types.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
  

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Platform\Platform.Lib.csproj" />
    <ProjectReference Include="..\Catalog.Core\Catalog.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Persistence\PostgreSQL\Migrations\" />
    <Folder Include="Persistence\SQLServer\Migrations\" />
  </ItemGroup>
	

	
</Project>
