<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

	<ItemGroup>
		<Protobuf Include="..\..\..\Contracts\discount.proto" GrpcServices="Server" Link="Protos\discount.proto" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.83.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.83.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.24.2-preview.1" />
  </ItemGroup>


	<ItemGroup>
		<ProjectReference Include="..\..\..\Platform\Platform.API\Platform.API.csproj" />
	</ItemGroup>


</Project>
