{{- if .Values.apps.rabbitmq.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: ecommerce
  labels:
    app: rabbitmq

spec:
  replicas: 1

  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq

    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.2-management

          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP

            - name: management
              containerPort: 15672
              protocol: TCP

          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: RABBITMQ_DEFAULT_USER

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config
                  key: RABBITMQ_DEFAULT_PASS

            - name: RABBITMQ_LOGS
              value: "-"

            - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
              value: "-rabbit log [{console,[{level,warning}]}]"

          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi

          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq

          # Allows RabbitMQ enough time to complete startup.
          startupProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 30

          # Controls whether the Pod receives traffic.
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3

          # Restarts the container if RabbitMQ becomes unhealthy.
          livenessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - ping
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3

      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
{{- end }}