apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  namespace: ecommerce
  labels:
    app: gateway-api

spec:
  type: ClusterIP

  selector:
    app: gateway-api

  ports:
    # Public Gateway
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

    # Internal Gateway endpoint
    - name: internal
      port: 81
      targetPort: internal
      protocol: TCP

    # Internal management/metrics
    - name: management
      port: 82
      targetPort: management
      protocol: TCP
